name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  helpppp:

    env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }} 

    runs-on: ubuntu-latest

    steps:
     
        
          - uses: actions/checkout@v3
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'adopt'

          - uses: actions/checkout@v3
          - name: update project varsion
            working-directory: my-app
            run: | 
                  chmod +x ./change_version.sh          
                  ./change_version.sh
             
          - name: set version var
            working-directory: my-app
            run: |
                  echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

          - name: Build the Docker image
            working-directory: my-app


            run: |
                  echo $docker_repo
                  docker build -t $DOCKER_USER/hello_world_test:$version --build-arg value=$version .

          - name: login to DockerHub

            run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS

          - name: push to DockerHub

            run: |
                  docker push $DOCKER_USER/hello_world_test:$version 

          - name: run application
            run: |
                docker run $DOCKER_USER/hello_world_test:$version

          

          